version: '3.8'

services:
  web:
    build: .
    container_name: threejs-app
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./css/style.css:/usr/share/nginx/html/css/style.css
      - ./js/script.js:/usr/share/nginx/html/js/script.js
      - ./nginx.conf:/etc/nginx/nginx.conf 
    restart: always
